services:
  mongo:
    image: mongo:latest
    ports: 
      - "27018:27017"

  backend:
    build: ./backend
    ports:
      - "4999:4999"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
